##Spring Configuration
server:
  port: 8081
spring:
  application:
    name: CrediYAReportsService
  devtools:
    add-properties: false
adapters:
  r2dbc:
    host: localhost
    port: 3307
    database: crediya_loan_requests
    username: crediya_loan_requests_user
    password: crediya_loan_requests_pass