server:
  port: 8080
spring:
  application:
    name: "CrediYAReportsService"
  devtools:
    add-properties: false
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
app:
  tz: "${APP_TZ:UTC}"
cors:
  allowed-origins: "${CORS_ALLOWED_ORIGINS}"
jwt:
  secret: "${JWT_SECRET}"
aws:
  region: "${AWS_DEFAULT_REGION}"
entrypoint:
  sqs:
    region: "${AWS_DEFAULT_REGION}"
    approvedQueueUrl: "${AWS_SQS_LOAN_APPLICATIONS_APPROVED_QUEUE_URL}"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
adapter:
  sqs:
    region: "${AWS_DEFAULT_REGION}"
    metricsNotificationQueueUrl: "${AWS_SQS_LOAN_APPLICATIONS_APPROVED_METRICS_QUEUE_URL}"
